# Comparing sentimental analysis for out final manual & influencial labelled data

## 1.0 - Selecting sub-set of columns for publishing dataset



In [1]:
import warnings
warnings.filterwarnings('ignore')

In [2]:
#import pandas as pd
#df = pd.read_excel("20220422_FULLDATASET_final_manual_influencial_labelling_v7.xlsx")

In [3]:
#df['id']= df.index

In [4]:
#df.columns

In [5]:
#df[['id','date','news','final_manual_labelling','text_span']].\
#to_csv("CryptoLin.csv",index=False)

#df[['id','date','news','final_manual_labelling','text_span']].\
#to_excel("CryptoLin.xlsx",index=False)

## 2.0 - Calculating several Sentiment Analysis

### Vader Sentiment Analysis

In [6]:
import pandas as pd
df = pd.read_csv("CryptoLin.csv")

In [7]:
!pip install vaderSentiment
from vaderSentiment.vaderSentiment import SentimentIntensityAnalyzer
vader = SentimentIntensityAnalyzer()
df['vader'] = df['news'].apply(lambda x: vader.polarity_scores(x)['compound'])

Defaulting to user installation because normal site-packages is not writeable


In [8]:
df

id       date                                               news  \
0        0  1/25/2022  Ripple announces stock buyback, nabs $15 billi...   
1        1  1/25/2022  IMF directors urge El Salvador to remove Bitco...   
2        2  1/25/2022  Dragonfly Capital is raising $500 million for ...   
3        3  1/25/2022  Rick and Morty co-creator collaborates with Pa...   
4        4  1/25/2022                 How fintech SPACs lost their shine   
...    ...        ...                                                ...   
2678  2678   5/1/2020  Gambling for a good cause – CryptoSlots donate...   
2679  2679  4/18/2020       Litecoin, The Chinese Alternative to Bitcoin   
2680  2680  4/10/2020            Do You Know What is Happening to Money?   
2681  2681  7/30/2018            Download CoinMarketCal app on App Store   
2682  2682  7/30/2018          Download CoinMarketCal app on Google Play   

      final_manual_labelling  \
0                          1   
1                         -1   
2                          1   
3                          0   
4                          0   
...                      ...   
2678                       1   
2679                       0   
2680                       0   
2681                       0   
2682                       0   

                                              text_span   vader  
0     {annotator1_id:6;annotator1_label:1; annotator...  0.0000  
1     {annotator1_id:16;annotator1_label:-1; annotat...  0.1280  
2     {annotator1_id:22;annotator1_label:1; annotato...  0.0000  
3     {annotator1_id:15;annotator1_label:0; annotato...  0.0000  
4     {annotator1_id:8;annotator1_label:0; annotator... -0.3182  
...                                                 ...     ...  
2678  {annotator1_id:27;annotator1_label:1; annotato...  0.0772  
2679  {annotator1_id:8;annotator1_label:0; annotator...  0.0000  
2680  {annotator1_id:16;annotator1_label:0; annotato...  0.0000  
2681  {annotator1_id:11;annotator1_label:0; annotato...  0.0000  
2682  {annotator1_id:21;annotator1_label:0; annotato...  0.3400  

[2683 rows x 6 columns]

In [9]:
df.to_excel("FULLDATASET_FOR_ANALYSIS.xlsx",index=False)

### Textblob Sentiment Analysis

In [10]:
!pip install textblob
from textblob import TextBlob
df['textblob'] = df['news'].apply(lambda x: TextBlob(x).sentiment.polarity)



Defaulting to user installation because normal site-packages is not writeable


In [11]:
df.to_excel("FULLDATASET_FOR_ANALYSIS.xlsx",index=False)

In [12]:
## Calculating manual_influencial_labelling

### Flair Sentiment Analysis

In [13]:
!pip install flair

Defaulting to user installation because normal site-packages is not writeable


In [14]:
from flair.models import TextClassifier
from flair.data import Sentence

In [15]:
classifier = TextClassifier.load('en-sentiment')

2022-05-31 15:15:43,071 loading file C:\Users\manoe\.flair\models\sentiment-en-mix-distillbert_4.pt


In [16]:

def apply_fair(x):
    sentence = Sentence(x)
    classifier.predict(sentence)
    return sentence.labels[0].to_dict()['confidence']

In [17]:
apply_fair('The food was great!')



0.9961493015289307

In [18]:
df['flair'] = df['news'].apply(lambda x: apply_fair(x))

In [19]:
df

id       date                                               news  \
0        0  1/25/2022  Ripple announces stock buyback, nabs $15 billi...   
1        1  1/25/2022  IMF directors urge El Salvador to remove Bitco...   
2        2  1/25/2022  Dragonfly Capital is raising $500 million for ...   
3        3  1/25/2022  Rick and Morty co-creator collaborates with Pa...   
4        4  1/25/2022                 How fintech SPACs lost their shine   
...    ...        ...                                                ...   
2678  2678   5/1/2020  Gambling for a good cause – CryptoSlots donate...   
2679  2679  4/18/2020       Litecoin, The Chinese Alternative to Bitcoin   
2680  2680  4/10/2020            Do You Know What is Happening to Money?   
2681  2681  7/30/2018            Download CoinMarketCal app on App Store   
2682  2682  7/30/2018          Download CoinMarketCal app on Google Play   

      final_manual_labelling  \
0                          1   
1                         -1   
2                          1   
3                          0   
4                          0   
...                      ...   
2678                       1   
2679                       0   
2680                       0   
2681                       0   
2682                       0   

                                              text_span   vader  textblob  \
0     {annotator1_id:6;annotator1_label:1; annotator...  0.0000  0.000000   
1     {annotator1_id:16;annotator1_label:-1; annotat...  0.1280  0.200000   
2     {annotator1_id:22;annotator1_label:1; annotato...  0.0000  0.136364   
3     {annotator1_id:15;annotator1_label:0; annotato...  0.0000  0.000000   
4     {annotator1_id:8;annotator1_label:0; annotator... -0.3182  0.000000   
...                                                 ...     ...       ...   
2678  {annotator1_id:27;annotator1_label:1; annotato...  0.0772  0.418182   
2679  {annotator1_id:8;annotator1_label:0; annotator...  0.0000  0.000000   
2680  {annotator1_id:16;annotator1_label:0; annotato...  0.0000  0.000000   
2681  {annotator1_id:11;annotator1_label:0; annotato...  0.0000  0.000000   
2682  {annotator1_id:21;annotator1_label:0; annotato...  0.3400  0.000000   

         flair  
0     0.875877  
1     0.998796  
2     0.984027  
3     0.996666  
4     0.999921  
...        ...  
2678  0.740891  
2679  0.992594  
2680  0.998091  
2681  0.554650  
2682  0.508411  

[2683 rows x 8 columns]

In [20]:
df.to_excel("FULLDATASET_FOR_ANALYSIS.xlsx",index=False)

### FinBERT Sentiment Analysis
ref: https://wandb.ai/ivangoncharov/FinBERT_Sentiment_Analysis_Project/reports/Financial-Sentiment-Analysis-on-Stock-Market-Headlines-With-FinBERT-Hugging-Face--VmlldzoxMDQ4NjM0

HuggingFace makes it really easy for us to try out different NLP models. We can find the FinBERT model on the HuggingFace model hub (https://huggingface.co/ProsusAI/finbert) & even run a test inference using a little text box right on their website (https://huggingface.co/ProsusAI/finbert)! 

In [21]:
!pip install transformers

Defaulting to user installation because normal site-packages is not writeable


In [22]:
from transformers import AutoTokenizer, AutoModelForSequenceClassification
  
tokenizer = AutoTokenizer.from_pretrained("ProsusAI/finbert")
model = AutoModelForSequenceClassification.from_pretrained("ProsusAI/finbert")

In [23]:
import torch

def apply_finbert(x):
#    return (0,1,2)
    inputs = tokenizer([x], padding = True, truncation = True, return_tensors='pt')
    outputs = model(**inputs)
    predictions = torch.nn.functional.softmax(outputs.logits, dim=1) 
    return predictions[:, 0].tolist()[0], predictions[:, 1].tolist()[0], predictions[:, 2].tolist()[0]

#    if  (predictions[:, 0].tolist() > predictions[:, 1].tolist()\
#        and predictions[:, 0].tolist() > predictions[:, 2].tolist()):# Returns a greater than 1 if it is positive 
#        return 1 + predictions[:, 0].tolist()[0]
#    elif (predictions[:, 1].tolist() > predictions[:, 0].tolist()\
#        and predictions[:, 1].tolist() > predictions[:, 2].tolist()):# Returns a number smaller than 1 if it is negative
#        return predictions[:, 0].tolist()[0]
#    else:
#        return predictions[:, 2].tolist()[0]



apply_finbert(df.iloc[0,2])

(0.09828820824623108, 0.020569320768117905, 0.8811424374580383)

In [24]:
#apply_finbert(df.iloc[0,2])[:, 2].tolist() + apply_finbert(df.iloc[0,2])[:, 0].tolist() + apply_finbert(df.iloc[0,2])[:, 1].tolist()  

In [25]:
df['finbert_positive'],df['finbert_negative'],df['finbert_neutral'] = zip(*df['news'].apply(lambda x: apply_finbert(x)))


In [26]:
df

id       date                                               news  \
0        0  1/25/2022  Ripple announces stock buyback, nabs $15 billi...   
1        1  1/25/2022  IMF directors urge El Salvador to remove Bitco...   
2        2  1/25/2022  Dragonfly Capital is raising $500 million for ...   
3        3  1/25/2022  Rick and Morty co-creator collaborates with Pa...   
4        4  1/25/2022                 How fintech SPACs lost their shine   
...    ...        ...                                                ...   
2678  2678   5/1/2020  Gambling for a good cause – CryptoSlots donate...   
2679  2679  4/18/2020       Litecoin, The Chinese Alternative to Bitcoin   
2680  2680  4/10/2020            Do You Know What is Happening to Money?   
2681  2681  7/30/2018            Download CoinMarketCal app on App Store   
2682  2682  7/30/2018          Download CoinMarketCal app on Google Play   

      final_manual_labelling  \
0                          1   
1                         -1   
2                          1   
3                          0   
4                          0   
...                      ...   
2678                       1   
2679                       0   
2680                       0   
2681                       0   
2682                       0   

                                              text_span   vader  textblob  \
0     {annotator1_id:6;annotator1_label:1; annotator...  0.0000  0.000000   
1     {annotator1_id:16;annotator1_label:-1; annotat...  0.1280  0.200000   
2     {annotator1_id:22;annotator1_label:1; annotato...  0.0000  0.136364   
3     {annotator1_id:15;annotator1_label:0; annotato...  0.0000  0.000000   
4     {annotator1_id:8;annotator1_label:0; annotator... -0.3182  0.000000   
...                                                 ...     ...       ...   
2678  {annotator1_id:27;annotator1_label:1; annotato...  0.0772  0.418182   
2679  {annotator1_id:8;annotator1_label:0; annotator...  0.0000  0.000000   
2680  {annotator1_id:16;annotator1_label:0; annotato...  0.0000  0.000000   
2681  {annotator1_id:11;annotator1_label:0; annotato...  0.0000  0.000000   
2682  {annotator1_id:21;annotator1_label:0; annotato...  0.3400  0.000000   

         flair  finbert_positive  finbert_negative  finbert_neutral  
0     0.875877          0.098288          0.020569         0.881142  
1     0.998796          0.047823          0.162971         0.789206  
2     0.984027          0.156997          0.008097         0.834906  
3     0.996666          0.055608          0.015489         0.928903  
4     0.999921          0.039964          0.472788         0.487248  
...        ...               ...               ...              ...  
2678  0.740891          0.178831          0.008580         0.812589  
2679  0.992594          0.105272          0.009314         0.885414  
2680  0.998091          0.027453          0.304318         0.668229  
2681  0.554650          0.046135          0.015244         0.938621  
2682  0.508411          0.042141          0.017657         0.940202  

[2683 rows x 11 columns]

In [27]:
df.to_excel("FULLDATASET_FOR_ANALYSIS.xlsx",index=False)

## 3.0 - Performing Comparison
### 3.1 - Finiding the best but-off for each Sentimental Analysis for all days and news

In [28]:
import pandas as pd
df = pd.read_excel("FULLDATASET_FOR_ANALYSIS.xlsx")


In [29]:
#df['finbert_negative'] = -df['finbert_negative']
# Best finbert compound! Tried many combinations!
df['finbert'] = df['finbert_positive']-df['finbert_negative']+df['finbert_neutral']
df['finbert_negative'] = -df['finbert_negative'] #Turnig negative Finbert around

In [30]:
y = df['final_manual_labelling']

In [31]:
y_positive_or_else = df['final_manual_labelling'].apply(lambda x: 1 if x > 0 else 0)
y_else_or_negative = df['final_manual_labelling'].apply(lambda x: 0 if x < 0 else 1)

In [32]:
#https://machinelearningmastery.com/threshold-moving-for-imbalanced-classification/
from sklearn.metrics import roc_curve, confusion_matrix

In [33]:
best_negative_threshold, best_positive_threshold = 0, 0
def apply_cutoff(x):
    
    if x < best_negative_threshold:
        return -1
    elif x > best_positive_threshold:
        return 1
    else:
        return 0

from numpy import sqrt, argmax
from numpy import sqrt, argmax
from sklearn.metrics import accuracy_score, classification_report
for prediction_name in ['vader','textblob','flair','finbert_positive','finbert_negative','finbert_neutral','finbert']:
    fpr, tpr, thresholds = roc_curve(y_positive_or_else, df[prediction_name])
    gmeans = sqrt(tpr * (1-fpr))
    ix = argmax(gmeans)
    best_positive_threshold = thresholds[ix]
    best_positive_threshold

    fpr, tpr, thresholds = roc_curve(y_else_or_negative, df[prediction_name])
    
    gmeans = sqrt(tpr * (1-fpr))
    ix = argmax(gmeans)
    best_negative_threshold = thresholds[ix]
    
    
    df[prediction_name+"_class"] = df[prediction_name].apply(apply_cutoff)
    
    accuracy = accuracy_score(y, df[prediction_name+"_class"])
    
    print("prediction_name=",prediction_name)
    print("best_negative_threshold =", best_negative_threshold, " / best_positive_threshold =", \
          best_positive_threshold, " / accuracy =", accuracy)
    print("classification_report:")
    print(classification_report(y, df[prediction_name+"_class"]))
    print("confusion_matrix - counts:")
    print(confusion_matrix(y, df[prediction_name+"_class"]))#, normalize='all'))
    print("confusion_matrix - percentage of total:")
    print(confusion_matrix(y, df[prediction_name+"_class"], normalize='all'))
    print("-"*50)

prediction_name= vader
best_negative_threshold = 0.0  / best_positive_threshold = 0.0258  / accuracy = 0.4476332463660082
classification_report:
              precision    recall  f1-score   support

          -1       0.48      0.46      0.47       346
           0       0.41      0.61      0.49      1061
           1       0.52      0.31      0.39      1276

    accuracy                           0.45      2683
   macro avg       0.47      0.46      0.45      2683
weighted avg       0.47      0.45      0.44      2683

confusion_matrix - counts:
[[160 124  62]
 [118 642 301]
 [ 58 819 399]]
confusion_matrix - percentage of total:
[[0.05963474 0.04621692 0.02310846]
 [0.04398062 0.23928438 0.11218785]
 [0.02161759 0.30525531 0.14871413]]
--------------------------------------------------
prediction_name= textblob
best_negative_threshold = 0.005681818181818177  / best_positive_threshold = 0.005681818181818177  / accuracy = 0.2527021990309355
classification_report:
              precisio

### 3.2 - Finiding the best but-off for each Sentimental Analysis for ONLY RELEVANT days ACCORDING TO FAMA FRENCH, for this group we use 

In [34]:
df=df[df['type_abnormal_return_fama_frech']!=0]

KeyError: 'type_abnormal_return_fama_frech'

In [ ]:
def remain_if_coincident(x,y):
    if x!=y:
        return 0
    else:
        return x

In [ ]:
import numpy as np
df['coincident_final_manual_labelling'] = np.vectorize(remain_if_coincident)(df['final_manual_labelling'],df['type_abnormal_return_fama_frech'])

In [ ]:
y = df['coincident_final_manual_labelling']
y_positive_or_else = df['final_manual_labelling'].apply(lambda x: 1 if x > 0 else 0)
y_else_or_negative = df['final_manual_labelling'].apply(lambda x: 0 if x < 0 else 1)

In [ ]:
best_negative_threshold, best_positive_threshold = 0, 0
def apply_cutoff(x):
    
    if x < best_negative_threshold:
        return -1
    elif x > best_positive_threshold:
        return 1
    else:
        return 0

from numpy import sqrt, argmax
from numpy import sqrt, argmax
from sklearn.metrics import accuracy_score, classification_report
for prediction_name in ['vader','textblob','flair','finbert_positive','finbert_negative','finbert_neutral','finbert']:
    fpr, tpr, thresholds = roc_curve(y_positive_or_else, df[prediction_name])
    gmeans = sqrt(tpr * (1-fpr))
    ix = argmax(gmeans)
    best_positive_threshold = thresholds[ix]
    best_positive_threshold

    fpr, tpr, thresholds = roc_curve(y_else_or_negative, df[prediction_name])
    
    gmeans = sqrt(tpr * (1-fpr))
    ix = argmax(gmeans)
    best_negative_threshold = thresholds[ix]
    
    
    df[prediction_name+"_class"] = df[prediction_name].apply(apply_cutoff)
    
    accuracy = accuracy_score(y, df[prediction_name+"_class"])
    
    print("prediction_name=",prediction_name)
    print("best_negative_threshold =", best_negative_threshold, " / best_positive_threshold =", \
          best_positive_threshold, " / accuracy =", accuracy)
    print("classification_report:")
    print(classification_report(y, df[prediction_name+"_class"]))
    print("confusion_matrix - counts:")
    print(confusion_matrix(y, df[prediction_name+"_class"]))#, normalize='all'))
    print("confusion_matrix - percentage of total:")
    print(confusion_matrix(y, df[prediction_name+"_class"], normalize='all'))
    print("-"*50)